import { WordCard } from '../wordCard/wordCard';

export interface CategoryInfo {
  categoryName: string,
  categoryId: number,
  words: WordCard[]
}

export const allCard : CategoryInfo[] = [
  {
    categoryName: 'Action (set A)',
    categoryId: 1,
    words: [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mp3',
        id: 1,
        categoryId: 1,
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mp3',
        id: 2,
        categoryId: 1,
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
        id: 3,
        categoryId: 1,
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
        id: 4,
        categoryId: 1,
      },
      {
        word: 'fish',
        translation: 'ловить рыбу',
        image: 'img/fish.jpg',
        audioSrc: 'audio/fish.mp3',
        id: 5,
        categoryId: 1,
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
        id: 6,
        categoryId: 1,
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
        id: 7,
        categoryId: 1,
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
        id: 8,
        categoryId: 1,
      },
    ],
  },
  {
    categoryName: 'Action (set B)',
    categoryId: 2,
    words: [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
        id: 9,
        categoryId: 2,
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
        id: 10,
        categoryId: 2,
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
        id: 11,
        categoryId: 2,
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
        id: 12,
        categoryId: 2,
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
        id: 13,
        categoryId: 2,
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
        id: 14,
        categoryId: 2,
      },
      {
        word: 'skip',
        translation: 'пропускать, прыгать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
        id: 15,
        categoryId: 2,
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
        id: 16,
        categoryId: 2,
      },
    ],
  },
  {
    categoryName: 'Action (set C)',
    categoryId: 3,
    words: [
      {
        word: 'eat',
        translation: 'кушать',
        image: 'img/eat.jpg',
        audioSrc: 'audio/eat.mp3',
        id: 17,
        categoryId: 3,
      },
      {
        word: 'wash',
        translation: 'мыться',
        image: 'img/wash.png',
        audioSrc: 'audio/wash.mp3',
        id: 18,
        categoryId: 3,
      },
      {
        word: 'drink',
        translation: 'пить',
        image: 'img/drink.jpg',
        audioSrc: 'audio/drink.mp3',
        id: 19,
        categoryId: 3,
      },
      {
        word: 'sleep',
        translation: 'спать',
        image: 'img/sleep.jpg',
        audioSrc: 'audio/sleep.mp3',
        id: 20,
        categoryId: 3,
      },
      {
        word: 'read',
        translation: 'читать',
        image: 'img/read.jpg',
        audioSrc: 'audio/read.mp3',
        id: 21,
        categoryId: 3,
      },
      {
        word: 'watch',
        translation: 'смотреть',
        image: 'img/watch.jpg',
        audioSrc: 'audio/watch.mp3',
        id: 22,
        categoryId: 3,
      },
      {
        word: 'dress',
        translation: 'надевать',
        image: 'img/dress1.jpg',
        audioSrc: 'audio/dress.mp3',
        id: 23,
        categoryId: 3,
      },
      {
        word: 'smell',
        translation: 'вдыхать',
        image: 'img/smell.jpg',
        audioSrc: 'audio/smell.mp3',
        id: 24,
        categoryId: 3,
      },
    ],
  },
  {
    categoryName: 'Adjective',
    categoryId: 4,
    words: [
      {
        word: 'slow',
        translation: 'медленный',
        image: 'img/slow.jpg',
        audioSrc: 'audio/slow.mp3',
        id: 25,
        categoryId: 4,
      },
      {
        word: 'honey',
        translation: 'милый',
        image: 'img/honey.jpg',
        audioSrc: 'audio/honey.mp3',
        id: 26,
        categoryId: 4,
      },
      {
        word: 'long',
        translation: 'длинный',
        image: 'img/long.jpg',
        audioSrc: 'audio/long.mp3',
        id: 27,
        categoryId: 4,
      },
      {
        word: 'big',
        translation: 'большой',
        image: 'img/big.jpg',
        audioSrc: 'audio/big.mp3',
        id: 28,
        categoryId: 4,
      },
      {
        word: 'dirty',
        translation: 'грязный',
        image: 'img/dirty.jpg',
        audioSrc: 'audio/dirty.mp3',
        id: 29,
        categoryId: 4,
      },
      {
        word: 'sturdy',
        translation: 'сильный',
        image: 'img/strong.jpg',
        audioSrc: 'audio/sturdy.mp3',
        id: 30,
        categoryId: 4,
      },
      {
        word: 'ugly',
        translation: 'некрасивый',
        image: 'img/ugly.jpg',
        audioSrc: 'audio/ugly.mp3',
        id: 31,
        categoryId: 4,
      },
      {
        word: 'slim',
        translation: 'стройный',
        image: 'img/slim.jpg',
        audioSrc: 'audio/slim.mp3',
        id: 32,
        categoryId: 4,
      },
    ],
  },
  {
    categoryName: 'Animal (set A)',
    categoryId: 5,
    words: [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
        id: 33,
        categoryId: 5,
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
        id: 34,
        categoryId: 5,
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
        id: 35,
        categoryId: 5,
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
        id: 36,
        categoryId: 5,
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
        id: 37,
        categoryId: 5,
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
        id: 38,
        categoryId: 5,
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
        id: 39,
        categoryId: 5,
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
        id: 40,
        categoryId: 5,
      },
    ],
  },
  {
    categoryName: 'Animal (set B)',
    categoryId: 6,
    words: [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
        id: 41,
        categoryId: 6,
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mp3',
        id: 42,
        categoryId: 6,
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mp3',
        id: 43,
        categoryId: 6,
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mp3',
        id: 44,
        categoryId: 6,
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mp3',
        id: 45,
        categoryId: 6,
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mp3',
        id: 46,
        categoryId: 6,
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mp3',
        id: 47,
        categoryId: 6,
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mp3',
        id: 48,
        categoryId: 6,
      },
    ],
  },
  {
    categoryName: 'Clothes',
    categoryId: 7,
    words: [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mp3',
        id: 49,
        categoryId: 7,
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mp3',
        id: 50,
        categoryId: 7,
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mp3',
        id: 51,
        categoryId: 7,
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mp3',
        id: 52,
        categoryId: 7,
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mp3',
        id: 53,
        categoryId: 7,
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mp3',
        id: 54,
        categoryId: 7,
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mp3',
        id: 55,
        categoryId: 7,
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mp3',
        id: 56,
        categoryId: 7,
      },
    ],
  },
  {
    categoryName: 'Emotions',
    categoryId: 8,
    words: [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mp3',
        id: 57,
        categoryId: 8,
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mp3',
        id: 58,
        categoryId: 8,
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mp3',
        id: 59,
        categoryId: 8,
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mp3',
        id: 60,
        categoryId: 8,
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mp3',
        id: 61,
        categoryId: 8,
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mp3',
        id: 62,
        categoryId: 8,
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mp3',
        id: 63,
        categoryId: 8,
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mp3',
        id: 64,
        categoryId: 8,
      },
    ],
  },
];
